screen:
  native-width: 1680
  native-height: 960
  width: 1280
  height: 720

logging:
  game:
    level: 20 # 0, 10 DEBUG, 20 INFO, 30 WARNING, 40 ERROR, 50 CRITICAL
  trainer:
    level: 21 # 0, 10 DEBUG, 20 INFO, 30 WARNING, 40 ERROR, 50 CRITICAL
  mcts:
    level: 21 # 0, 10 DEBUG, 20 INFO, 30 WARNING, 40 ERROR, 50 CRITICAL

simulation:
  command-line-mode:
    enable: false # true | false ## OVERRIDE by command-line-mode to false
  rendering:
    enable: true # true | false ## OVERRIDE by command-line-mode to false
  actions:
    rendering:
      enable: true # true | false ## OVERRIDE by command-line-mode to false
  f-key-action: random # current | random
  framerate: 60
  auto-next-round: true # true | false ## OVERRIDE by command-line-mode to true
  round: 1
  output:
    enable: true # true | false
    dir: output # str
  multiprocessing:
    enable: false # true | false
    core: 8

agent:
  require-key-hold: false # true | false ## OVERRIDE by command-line-mode to false
  marquise:
    enable: true # true | false
    type: mcts # random | mcts ## random ignores all fields under mcts
    mcts:
      type: mcts # one-depth | mcts ## one-depth is janky, don't use
      reward-function: vp-difference # win | vp-difference | vp-difference-relu | vp-difference-bin
      expand-count: 200 # int
      rollout-no: 1 # int
      time-limit: -1 # float (per-rollout in milliseconds) (negative for no limit)
      action-count-limit: 100 # int (negative for no limit)
      best-action-policy: max
        # max - Select the root child with the highest reward
        # robust - Select the most visited root child.
        # UCB - Select the child which maximises the upper confidence bound.
        ## secure - Select the child which maximises the lower confidence bound.
  eyrie:
    enable: true
    type: mcts
    mcts:
      type: mcts
      reward-function: vp-difference
      expand-count: 00
      rollout-no: 1
      time-limit: -1
      action-count-limit: 20
      best-action-policy: robust


game:
  rendering:
    enable: true # true | false ## OVERRIDE by command-line-mode to false
  victory-point-limit: 30
  allow-dominance-card: false # true | false
