screen:
  native-width: 1680
  native-height: 960
  width: 1280
  height: 720

simulation:
  rendering:
    enable: true # true | false
  actions:
    rendering:
      enable: true # true | false
  f-key-action: random # current | random
  framerate: 60
  auto-next-round: true # true | false
  round: 50
  output:
    enable: false # true | false
    dir: output # str
  multiprocessing:
    enable: true # true | false
    core: 4

agent:
  require-key-hold: true # true | false
  marquise:
    enable: true # true | false
    type: mcts # random | mcts | rnn
    mcts:
      type: mcts # one-depth | mcts
      reward-function: vp-difference # win | vp-difference
      expand-count: 100 # int
      rollout-no: 1 # int
      time-limit: 1000 # float (per-rollout in milliseconds) (negative for no limit)
      action-count-limit: 20 # int (negative for no limit)
  eyrie:
    enable: true
    type: mcts
    mcts:
      type: mcts # one-depth | mcts
      reward-function: vp-difference # win | vp-difference
      expand-count: 50 # int
      rollout-no: 1 # int
      time-limit: -1 # float (per-rollout in milliseconds) (negative for no limit)
      action-count-limit: 20 # int (negative for no limit)

game:
  rendering:
    enable: true # true | false
  victory-point-limit: 30
  allow-dominance-card: false # true | false