screen:
  width: 1680
  height: 960

simulation:
  rendering:
    enable: true # true | false
  actions:
    rendering:
      enable: false # true | false
  f-key-action: random # current | random
  framerate: 1000
  auto-next-round: true # true | false
  round: 50
  output:
    enable: true # true | false
    dir: output # str

agent:
  require-key-hold: false # true | false
  marquise:
    enable: true # true | false
    type: mcts # random | mcts | rnn
    mcts:
      type: mcts # one-depth | mcts
      reward-function: vp-difference # win | vp-difference
      rollout-no: 100 # int
      time-limit: 10 # float (per-rollout in milliseconds)
  eyrie:
    enable: true
    type: random
    mcts:
      type: mcts # one-depth | mcts
      reward-function: vp-difference # win | vp-difference
      rollout-no: 100 # int
      time-limit: 10 # float (per-rollout in milliseconds)

game:
  rendering:
    enable: false # true | false
  victory-point-limit: 30
  allow-dominance-card: false # true | false