screen:
  width: 1680
  height: 960

simulation:
  rendering:
    enable: true # true | false
  actions:
    rendering:
      enable: true # true | false
  f-key-action: random # current | random
  framerate: 60
  auto-next-round: false # true | false
  round: 1000
  output:
    enable: false # true | false
    dir: output # str

agent:
  require-key-hold: true # true | false
  marquise:
    enable: false # true | false
    type: random # random | mcts | rnn
  eyrie:
    enable: true
    type: random

game:
  rendering:
    enable: true # true | false
  victory-point-limit: 30
  allow-dominance-card: true # true | false