screen:
  width: 1680
  height: 960
simulation:
  f-key-action: random # current | random
  framerate: 60

agent:
  require-key-hold: false # true | false
  marquise:
    use-agent: true # true | false
    agent-type: random # random | mcts | rnn
  eyrie:
    use-agent: true
    agent-type: random

game:
  victory-point-limit: 30
  allow-dominance-card: false # true | false